# Copyright 2020 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

#
# Get patterns for output filtering for CycloneDDS RMW.
#
# :param output_patterns: patterns that will be used to identify console output
# generated by CycloneDDS. :type output_filter: string
#
# @public
#
# 定义一个名为 get_rmw_cyclonedds_output_filter 的宏 (Define a macro named
# get_rmw_cyclonedds_output_filter)
macro(get_rmw_cyclonedds_output_filter output_patterns)
  # 如果传入的参数不为空 (If the passed arguments are not empty)
  if(NOT "${ARGN}" STREQUAL "")
    # 输出一个致命错误，说明调用 get_rmw_cyclonedds_output_filter() 时有未使用的参数 (Output a fatal
    # error, indicating that there are unused arguments when calling
    # get_rmw_cyclonedds_output_filter())
    message(FATAL_ERROR "get_rmw_cyclonedds_output_filter() called with "
                        "unused arguments: ${ARGN}")
  endif()

  # 设置 output_patterns 变量的值为一个正则表达式字符串 (Set the value of the output_patterns
  # variable to a regular expression string)
  set(${output_patterns}
      ".*using network interface \w+ \(.*\) selected arbitrarily from:.*")
endmacro()
